module LUutils

using Z2Algebra: Z2Block, blockgetindex_mask, blocktailsize_to_size, blockgetindex

"""
    find_first_nonzero(blocks, blockcol, col)

Find the first non-zero element in the column `col` of the block matrix `blocks` starting from block `blockcol`. Returns `(blockrow, row)`. Returns `(0, 0)` if the element is not found.
"""
function find_first_nonzero(blocks, blockcol, col)
    row = trailing_zeros(blocks[blockcol,blockcol].data & blockgetindex_mask(col:7, col)) ÷ 8
    if row < 8
        return (blockcol, row)
    end
    for blockrow in blockcol+1:size(blocks,1)
        row = trailing_zeros(blocks[blockrow,blockcol].data & blockgetindex_mask(:, col)) ÷ 8
        if row < 8
            return (blockrow, row)
        end
    end
    return (0, 0)
end

"""
    blockswaprows(a::Z2Block, maski, maskj, shift)

Swap two rows in a block and return the result block. `maski` and `maskj` are row masks generated by [`blockgetindex_mask`](@ref), and `shift` is the bit difference between the masks. The arguments are set in this way because `maski`, `maskj` and `shift` could be reused in `swaprows`(@ref).
"""
@inline function blockswaprows(a::Z2Block, maski, maskj, shift)
    x = a.data
    rowi = x & maski
    rowj = x & maskj
    return Z2Block(x ⊻ rowi ⊻ rowj ⊻ (rowi >> shift) ⊻ (rowj << shift))
end

"""
    blockswaprows(a::Z2Block, b::Z2Block, maski, maskj, shift)

Swap two rows in two blocks and return the result blocks.
"""
@inline function blockswaprows(a::Z2Block, b::Z2Block, maski, maskj, shift)
    x = a.data
    y = b.data
    rowi = x & maski
    rowj = y & maskj
    return (Z2Block(x ⊻ rowi ⊻ (rowj << shift)), Z2Block(y ⊻ rowj ⊻ (rowi >> shift)))
end

"""
    swaprows!(blocks, blockcol, col, blockrow, row)

Swap two rows in `blocks` in the LU process. `blockcol`, `col`, `blockrow` and `row` are the indices of the pivot. The pivot and the entries to its right should be swapped to the row such that the pivot is in the diagonal.
"""
function swaprows!(blocks, blockcol, col, blockrow, row)
    shift = 8(col - row)
    maskdest = blockgetindex_mask(col, :)
    masksrc = blockgetindex_mask(row, :)
    if blockcol == blockrow # swap within one block
        if iszero(shift)
            return
        end
        @inbounds for _blockcol in axes(blocks,2)
            blocks[blockcol,_blockcol] = blockswaprows(blocks[blockcol,_blockcol], maskdest, masksrc, shift)
        end
    else # swap between two blocks
        @inbounds for _blockcol in axes(blocks,2)
            blocks[blockcol,_blockcol], blocks[blockrow,_blockcol] = blockswaprows(blocks[blockcol,_blockcol], blocks[blockrow,_blockcol], maskdest, masksrc, shift)
        end
    end
end

"""
    eliminate_rows!(blocks::AbstractMatrix{Z2Block}, blockpivot, pivot, colbuffer::AbstractVector{UInt64})

For the pivot with index `(blockpivot, pivot)`, do a round of row elimination. `colbuffer` is pre-allocated to reduce allocation overhead, and its length should be at least `size(blocks,1)`.
"""
function eliminate_rows!(blocks::AbstractMatrix{Z2Block}, blockpivot, pivot, colbuffer::AbstractVector{UInt64})
    pivot_block = blocks[blockpivot, blockpivot].data
    pivot_rowvalue = (pivot_block >> unsigned(8pivot)) & blockgetindex_mask(0, pivot+1:7)
    pivot_colvalue = (pivot_block >> unsigned(pivot)) & blockgetindex_mask(pivot+1:7, 0)

    # pivot block
    blocks[blockpivot, blockpivot] = Z2Block(pivot_block ⊻ (pivot_colvalue * pivot_rowvalue))

    # blocks to the right
    @inbounds for blockcol in blockpivot+1:size(blocks,2)
        block = blocks[blockpivot, blockcol].data
        rowvalue = blockgetindex(block, pivot, :)
        blocks[blockpivot, blockcol] = Z2Block(block ⊻ (pivot_colvalue * rowvalue))
    end

    # blocks to the bottom
    @inbounds for blockrow in blockpivot+1:size(blocks,1)
        block = blocks[blockrow, blockpivot].data
        colvalue = blockgetindex(block, :, pivot)
        colbuffer[blockrow] = colvalue
        blocks[blockrow, blockpivot] = Z2Block(block ⊻ (colvalue * pivot_rowvalue))
    end

    # blocks to the bottom-right
    @inbounds for blockcol in blockpivot+1:size(blocks,2)
        rowvalue = blockgetindex(blocks[blockpivot, blockcol].data, pivot, :)
        for blockrow in blockpivot+1:size(blocks,1)
            block = blocks[blockrow, blockcol].data
            colvalue = colbuffer[blockrow]
            blocks[blockrow, blockcol] = Z2Block(block ⊻ (rowvalue * colvalue))
        end
    end     
end

end # module

function lu!(A::Z2Matrix, pivot::Union{RowMaximum,NoPivot,RowNonZero} = RowNonZero(); check = true, allowsingular = false)
    if pivot === NoPivot()
        throw(ArgumentError("NoPivot() is currently not supported for Z2Matrix"))
    end

    ipiv = collect(1:8*size(A.blocks,1))
    info = 0

    colbuffer = Vector{UInt64}(undef, size(A.blocks,1))
    for blockcol in Base.oneto(min(size(A.blocks)...))
        for col in 0:7
            (blockrow, row) = LUutils.find_first_nonzero(A.blocks, blockcol, col)

            if iszero(blockrow)
                if iszero(info)
                    info = blocktailsize_to_size(blockcol, col)
                end
                continue # no pivot in this column
            end

            LUutils.swaprows!(A.blocks, blockcol, col, blockrow, row)

            ipiv[blocktailsize_to_size(blockcol, col)] = blocktailsize_to_size(blockrow, row)

            LUutils.eliminate_rows!(A.blocks, blockcol, col, colbuffer)
        end
    end
    if info > size(A,1)
        info = 0
    end
    resize!(ipiv, size(A,1))
    check && LinearAlgebra._check_lu_success(info, allowsingular)

    return LU(A, ipiv, info)
end
