module LUutils

using Z2Algebra: Z2Block, blockgetindex_mask, blocktailsize_to_size, blockgetindex

"""
    find_first_nonzero(blocks, blockcol, col)

Find the first non-zero element in the column `col` of the block matrix `blocks` starting from block `blockcol`. Returns `(blockrow, row)`. Returns `(0, 0)` if the element is not found.
"""
function find_first_nonzero(blocks, blockcol, col)
    row = trailing_zeros(blocks[blockcol,blockcol].data & blockgetindex_mask(col:7, col)) ÷ 8
    if row < 8
        return (blockcol, row)
    end
    for blockrow in blockcol+1:size(blocks,1)
        row = trailing_zeros(blocks[blockrow,blockcol].data & blockgetindex_mask(:, col)) ÷ 8
        if row < 8
            return (blockrow, row)
        end
    end
    return (0, 0)
end

"""
    blockswaprows(a::Z2Block, maski, maskj, shift)

Swap two rows in a block and return the result block. `maski` and `maskj` are row masks generated by [`blockgetindex_mask`](@ref), and `shift` is the bit difference between the masks. The arguments are set in this way because `maski`, `maskj` and `shift` could be reused in `swaprows`(@ref).
"""
@inline function blockswaprows(a::Z2Block, maski, maskj, shift)
    x = a.data
    rowi = x & maski
    rowj = x & maskj
    return Z2Block(x ⊻ rowi ⊻ rowj ⊻ (rowi >> shift) ⊻ (rowj << shift))
end

"""
    blockswaprows(a::Z2Block, b::Z2Block, maski, maskj, shift)

Swap two rows in two blocks and return the result blocks.
"""
@inline function blockswaprows(a::Z2Block, b::Z2Block, maski, maskj, shift)
    x = a.data
    y = b.data
    rowi = x & maski
    rowj = y & maskj
    return (Z2Block(x ⊻ rowi ⊻ (rowj << shift)), Z2Block(y ⊻ rowj ⊻ (rowi >> shift)))
end

"""
    swaprows!(blocks, blockcol, col, blockrow, row)

Swap two rows in `blocks` in the LU process. `blockcol`, `col`, `blockrow` and `row` are the indices of the pivot. The pivot and the entries to its right should be swapped to the row such that the pivot is in the diagonal.
"""
function swaprows!(blocks, blockcol, col, blockrow, row)
    shift = 8(col - row)
    maskdest = blockgetindex_mask(col, :)
    masksrc = blockgetindex_mask(row, :)
    if blockcol == blockrow # swap within one block
        if iszero(shift)
            return
        end
        for _blockcol in axes(blocks,2)
            blocks[blockcol,_blockcol] = blockswaprows(blocks[blockcol,_blockcol], maskdest, masksrc, shift)
        end
    else # swap between two blocks
        for _blockcol in axes(blocks,2)
            blocks[blockcol,_blockcol], blocks[blockrow,_blockcol] = blockswaprows(blocks[blockcol,_blockcol], blocks[blockrow,_blockcol], maskdest, masksrc, shift)
        end
    end
end

"""
    eliminaterows!(blocks, blockpivot, pivot)

For the pivot with index `(blockpivot, pivot)`, do elimination in its own block, blocks to the right and below it. Other blocks to the bottom-right are bulk-updated by [`eliminate_rows_block!`](@ref) later.
"""
function eliminate_rows_first!(blocks, blockpivot, col, colbuffer)
    pivot_block = blocks[blockpivot, blockpivot].data
    pivot_rowvalue = (pivot_block >> 8col) & blockgetindex_mask(0, col+1:7)
    pivot_colvalue = (pivot_block >> col) & blockgetindex_mask(col+1:7, 0)

    # pivot block
    blocks[blockpivot, blockpivot] = Z2Block(pivot_block ⊻ (pivot_colvalue * pivot_rowvalue))

    # blocks to the right
    for blockcol in blockpivot+1:size(blocks,2)
        block = blocks[blockpivot, blockcol].data
        rowvalue = blockgetindex(block, col, :)
        blocks[blockpivot, blockcol] = Z2Block(block ⊻ (pivot_colvalue * rowvalue))
    end

    # blocks to the bottom
    for blockrow in blockpivot+1:size(blocks,1)
        block = blocks[blockrow, blockpivot].data
        colvalue = blockgetindex(block, :, col)
        colbuffer[blockrow] = colvalue
        blocks[blockrow, blockpivot] = Z2Block(block ⊻ (colvalue * pivot_rowvalue))
    end

    # blocks to the bottom-right
    for blockcol in blockpivot+1:size(blocks,2)
        rowvalue = blockgetindex(blocks[blockpivot, blockcol].data, col, :)
        for blockrow in blockpivot+1:size(blocks,1)
            @inbounds blocks[blockrow, blockcol] = Z2Block(blocks[blockrow, blockcol].data ⊻ (rowvalue * colbuffer[blockrow]))
        end
    end     
end

"""
    eliminate_rows_block!(blocks, blockrow)

Eliminate blocks below `blockrow` in the LU process. This basically packs 8 row eliminations at once.
"""
function eliminate_rows_block!(blocks, blockpivot)
    for blockcol in blockpivot+1:size(blocks,2)
        for blockrow in blockpivot+1:size(blocks,1)
            blocks[blockrow, blockcol] = blocks[blockrow, blockcol] + blocks[blockrow, blockpivot] * blocks[blockpivot, blockcol]
        end
    end
end

end # module
